# -*- coding: utf-8 -*-
"""Nápověda k nákladovým okruhům (Charakteristika).

Mapování kód nákladového okruhu -> název střediska.
Zdroj: HEO – Generátor mzdových sestav (export JIP.xlsx).
Aktualizace: stačí upravit/doplnit položky ve slovníku níže.
"""

NAKLADOVE_OKRUHY = {
    '019': 'Velkoobchod Čas',
    '019A': 'Čas Hodonín JIP',
    '026M': 'Ostrava gastro',
    '034': 'ELKO Plzeň',
    '037': 'Nová Role',
    '103': 'cash Jičín',
    '107': 'cash Slaný',
    '10J': 'Pardubice',
    '10X501': 'Centrála - vedení',
    '10X550': 'obchod-nákupčí',
    '10X551': 'obchod - klíčový zákazníci',
    '10x560A': 'Správa a vývoj IS',
    '10x560B': 'IT technik',
    '10x560C': 'IT podpora',
    '10x560N': 'IT podpora - Nálevka - NEPOUŽÍVAT',
    '10X570': 'Call centrum',
    '10X580': 'Centrální příjem',
    '10X582': 'Správa karet a letáky',
    '10x584A': 'Reporting',
    '10x584B': 'Centrální správa systému',
    '10X601': 'Účetní',
    '10X602': 'Účtárna',
    '10x603': 'Mzdové a personální oddělení',
    '10X609': 'Účtárna MO a CC',
    '10X650': 'Doprava centrála',
    '10X659': 'Doprava kamiony',
    '10X670': 'Grafici',
    '10X680': 'Supervizoři',
    '10Z': 'JIP majetková',
    '10ZS': 'JIP majetková stavba',
    '115': 'cash Horní Slavkov',
    '116': 'cash Karlovy Vary - Na Vyhlídce',
    '117': 'cash Sokolov',
    '11J': 'Praha',
    '11M': 'gastro Praha',
    '123': 'cash Chomutov Jiráskova',
    '12J': 'Jilemnice',
    '133': 'cash Sezemice',
    '139': 'cash Svoboda nad Úpou',
    '13J': 'Most',
    '140': 'cash Hrádek',
    '142': 'cash Harrachov',
    '145': 'cash Mariánské Lázně-Husova',
    '147': 'cash Žlutice',
    '148': 'cash Mariánské Lázně-Hroznatová',
    '14J': 'Liberec',
    '15': 'sklad bourárna',
    '154': 'cash Františkovy Lázně - Lidická',
    '163': 'cash Jáchymov',
    '165': 'cash Prachatice',
    '172': 'Sadská',
    '173': 'Blatná',
    '174': 'Špindlerův Mlýn',
    '175': 'Pardubice MO Smilova',
    '17J': 'Horšovský Týn',
    '20L': 'Lesko',
    '26N': 'Benstar Ostrava',
    '27N': 'Benstar Olomouc',
    '300': 'C&C Pardubice',
    '300A': 'C&C Pardubice pekárna',
    '302': 'C&C Praha Bořanovice',
    '302A': 'C&C Praha pekárna',
    '302C': 'C&C Praha cukrárna',
    '302D': 'C&C Praha lahůdky',
    '306': 'C&C Svoboda nad Úpou',
    '308': 'C&C Karlovy Vary',
    '308A': 'C&C Karlovy Vary Pekárna',
    '30J': 'Brno cross',
    '310': 'C&C  Sušice',
    '311': 'C&C Polička',
    '313': 'C&C  Náchod',
    '316': 'C&C Jilemnice',
    '316A': 'C&C Jilemnice pekárna',
    '318': 'Lesko prodejna',
    '318A': 'Lesko pekárna',
    '319': 'C&C Olomouc',
    '319A': 'C&C Olomouc pekárna',
    '319S': 'C&C Olomouc sushi',
    '31N': 'Benstar Jeseník',
    '320': 'Čas Cash Hodonín',
    '321': 'Čas Cash Břeclav',
    '325': 'Brno cash',
    '325A': 'Brno pekárna',
    '325B': 'Brno bistro+kavárna',
    '325G': 'Brno GRILL Point + Sekt',
    '325L': 'Brno mozzarela',
    '325R': 'Brno restaurace',
    '325S': 'Brno sushi',
    '325T': 'Brno pasta',
    '326': 'Ostrava cash',
    '326A': 'Ostrava pekárna',
    '326B': 'Ostrava bistro',
    '326C': 'Ostrava cukrárna',
    '326D': 'Ostrava lahůdky',
    '326K': 'Ostrava pražírna kávy',
    '326S': 'Ostrava sushi',
    '32F': 'Bikos',
    '33J': 'České Budějovice',
    '340': 'ELKO Plzeň Berounka',
    '341': 'ELKO Domažlice',
    '342': 'ELKO Kladno, BOX servis',
    '343': 'ELKO Kralovice',
    '344': 'ELKO Nepomuk',
    '345': 'ELKO Klatovy',
    '346': 'ELKO Cheb',
    '347': 'Kunčičky u Bašky',
}

# Vyhledávací mapa s klíči ve velkých písmenech (case-insensitive lookup)
_LOOKUP = {k.upper(): v for k, v in NAKLADOVE_OKRUHY.items()}


def nazev_okruhu(kod):
    """Vrátí název střediska pro kód nákladového okruhu, jinak prázdný řetězec."""
    if not kod:
        return ''
    return _LOOKUP.get(str(kod).strip().upper(), '')
