# -*- coding: utf-8 -*-
"""Seed data pro modul Vizitky a podpisy — vygenerováno z listu DATA
Excel formuláře (Formulář pro výrobu vizitek a podpisu.xlsx).
Slouží jen k naplnění editovatelných číselníků při PRVNÍM startu (prázdné tabulky).
Needituj ručně — číselníky se spravují v aplikaci."""

SEED_ODDELENI = [
    'Grafické oddělení',
    'Obchodní zástupce',
    'Vedoucí obchodních zástupců',
    'Vedoucí obchodního týmu',
    'Disponent',
    'Vedoucí pobočky',
    'Nákupní oddělení',
    'Obchodní ředitel',
    'IT - SW oddělení',
    'Obchodní oddělení',
    'Manager obchodního oddělení',
    'Vedoucí obchodních zástupců ASM',
    'Vedoucí prodeje',
    'Projektový manager IT',
    'Projektový manager IT -SW oddělení',
    'Sommelier',
    'Key Account Manager',
    'Management assistant',
    'Asistent prodeje',
    'Obchodní zástupce pro Retail',
    'Stavbyvedoucí',
    'Inspektor prodejen',
    'Vedoucí logistiky',
    'Vedoucí dopravy',
    'Vedoucí franšízové sítě',
    'Marketingový manažer',
    'Ředitel marketingu',
    'Asistent marketingu',
    'Konzultant v oblasti mražených krémů',
    'Vedoucí prodejny',
    'Supervizor',
    'Technolog pekáren',
    'Správa majetka, nemovitostí',
    'Vedoucí centrálního příjmu',
    'Dispečink',
    'Listing',
    'Letáky a listing',
    'Technik dopravy',
    'Asistent dopravy',
    'Asistent vedení společnosti / Management Assistant',
    'Oblastní vedoucí prodeje',
    'Vedení správy majetku, nemovitosti',
    'Centrální příjem',
    'Asistentka vedoucího pobočky',
    'Personální oddělení',
    'Call centrum',
    'Vedoucí obalárny',
    'Veducí administrativy',
    'Datový analytik',
    'Vedoucí datové analytiky',
    'IT - manager',
    'Oblastní vedoucí prodeje pro Gastro',
    'Vedoucí obchodního teamu - RETAIL',
    'Asistentka nákupního oddělení',
    'Asistentka dopravy',
    'Personální ředitel',
    'Ředitel provozu',
    'Fakturantka',
    'Mzdová účetní',
    'Manažer provozu',
    'Vedoucí skladu a dopravy',
    'Zástupce vedoucího obchodního oddělení',
    'Vedoucí gastro',
    'Zástupce vedoucího nákupního oddělení',
    'Vedoucí skladu',
    'Manažer pro klíčové zákazníky',
    'IT Technik',
    'Vedoucí – Interní alokace dokladů',
    'Referent – Interní alokace dokladů',
    'Vedoucí – Správa produktových karet',
    'Referent – Správa produktových karet',
    'Vedoucí – Správa zákaznických dat',
    'Referent – Správa zákaznických dat',
    'Manažerka datové analytiky a správy dat',
    'Vedoucí maloobchodní sítě',
    'Reklamace',
    'Řízený sklad',
    'IT Specialista',
    'Junior – Interní alokace dokladů',
    'Objednávky Praha',
    'Fakturace Praha',
    'Opravy Praha',
    'Vedoucí oprav a objednávek Praha',
    'Ekonomické oddělení',
    'Oddělení letáků',
    'Projektový manager',
]

SEED_POBOCKY = [
    'OVA',
    'PHA',
    'MST',
    'PLZ',
    'ZLN',
    'HOD',
    'OLO',
    'PCE',
    'JIL',
    'PLUS',
    'LIB',
    'NRO',
    'CBU',
    'PCE-grafici',
    'PCE-reznik',
    'PCE-sommelier',
    'PERS-pce',
    'BNO',
    'HOT',
    'PCE-doprava',
    'PCE-IT',
]

# (ulice, PSČ, město)
SEED_ADRESY = [
    ('Hradišťská 407', '533 52', 'Staré Hradiště'),
    ('Lípa 270', '763 11', 'Lípa'),
    ('Dělnická 37', '434 01', 'Most'),
    ('Hovorčovická 128', '250 65', 'Praha - Bořanovice'),
    ('Frýdecká 700/475', '719 00', 'Ostrava Hrabová'),
    ('Tovární 242', '362 25', 'Nová Role'),
    ('Na Výhoně 3682', '695 01', 'Hodonín'),
    ('Branská 918', '514 01', 'Jilemnice'),
    ('Nemanická 2180/3', '370 10', 'České Budějovice'),
    ('Šrámkova 132', '460 10', 'Liberec'),
    ('Lazecká 393/70a', '779 00', 'Olomouc'),
    ('Na zákopě 561', '779 00', 'Olomouc'),
    ('Libušínská 630/78', '326 00', 'Plzeň – Božkov'),
    ('Dusilov 22', '396 01', 'Humpolec'),
    ('Anglická 622', '463 34', 'Hrádek nad Nisou'),
    ('Úpská 14', '542 24', 'Svoboda nad Úpou'),
    ('Sportovní 574', '360 01', 'Karlovy Vary'),
    ('Hrádecká 1260', '342 01', 'Sušice'),
    ('Na Vyšehradě 1095', '572 01', 'Polička'),
    ('Plhovská 1098', '547 01', 'Náchod'),
    ('V Jilmu 229', '514 01', 'Jilemnice'),
    ('Jateční 169', '760 01', 'Zlín'),
    ('Holická1237/32', '779 00', 'Olomouc'),
    ('Pražákova 51', '619 00', 'Brno'),
    ('U Stadionu 3270', '690 02', 'Břeclav'),
    ('Nákupní 1447/7', '312 00', 'Plzeň -Berounka'),
    ('Masarykova 588', '344 01', 'Domažlice'),
    ('Nezamyslova 1432', '272 01', 'Kladno'),
    ('Manětínská 404', '331 41', 'Kralovice'),
    ('Kozlovická 539', '335 01', 'Nepomuk'),
    ('Dragounská 7', '339 01', 'Klatovy'),
    ('Dyleňská 2348/5', '350 02', 'Cheb'),
    ('Kunčičky u Bašky 386', '739 01', 'Kunčičky'),
    ('Valdštejnovo náměstí 5', '506 01', 'Jičín'),
    ('Dr. E. Beneše 527', '274 01', 'Slaný'),
    ('Dlouhá 12', '357 31', 'Horní Slavkov'),
    ('Na Vyhlídce 2025/52a', '360 01', 'Karlovy Vary'),
    ('Křížová 168', '356 01', 'Sokolov'),
    ('Jiráskova 4170', '430 03', 'Chomutov'),
    ('Mezi mosty 663', '533 04', 'Sezemice'),
    ('Rychorské sídliště 146', '542 24', 'Svoboda nad Úpou'),
    ('Harrachov 705', '512 46', 'Harrachov'),
    ('Husova 614/26', '353 01', 'Mariánské Lázně'),
    ('Pod Strání 507', '364 52', 'Žlutice'),
    ('Hroznatova 773/3', '353 01', 'Mariánské Lázně'),
    ('Lidická 393/17', '351 01', 'Františkovy Lázně'),
    ('K Lanovce 1055', '362 51', 'Jáchymov'),
    ('Nám. Přátelství 665', '383 01', 'Prachatice'),
    ('Palackého nám. 377', '289 12', 'Sadská'),
    ('J. P. Koubka 13', '388 01', 'Blatná'),
    ('Špindlerův Mlýn 121', '543 51', 'Špindlerův Mlýn'),
    ('Smilova 344', '530 02', 'Pardubice'),
    ('Nádražní 1298', '342 01', 'Sušice'),
]
